Dialog for cash donations
ChangePlusPlusVandy/MotherToMother pull request #202
Opened 2024-02-16 03:02 UTC by RachaelM13

![Screenshot 2024-02-15 205225](https://github.com/ChangePlusPlusVandy/MotherToMother/assets/115118738/1fe5eb29-45ce-4ad0-b3a7-089f57cc89c1)
![Screenshot 2024-02-15 205234](https://github.com/ChangePlusPlusVandy/MotherToMother/assets/115118738/c2a70926-933d-4dc0-a358-d75b0dc84d06)
![Screenshot 2024-02-15 205244](https://github.com/ChangePlusPlusVandy/MotherToMother/assets/115118738/2dd9c388-afdd-4b16-9dc8-35484c132e37)

2024-02-16 16:09 UTC, OliviaLiu417 requested changes

2024-02-16 16:09 UTC, OliviaLiu417 commented on Admin-Portal/src/components/cashDonations/cashDonationDialog.tsx
> +          {Object.values(CASHDONATION_TYPE).map((donor) => (
I think by selecting donor they want to see the specific organization instead of the generic type, so maybe query the db for the list of organizations and render them here instead

2024-02-16 16:09 UTC, OliviaLiu417 commented on Admin-Portal/src/lib/constants.tsx
> +export const CASHDONATION_TYPE = {
If we render the list of specific orgs we can get rid of this

2024-02-17 22:41 UTC, RachaelM13 commented
![image](https://github.com/ChangePlusPlusVandy/MotherToMother/assets/115118738/faa167ee-de41-4035-b665-669e07970874)

2024-02-19 17:33 UTC, OliviaLiu417 approved these changes

2024-02-19 17:34 UTC, merged