finished fine tuning, account type and agency
ChangePlusPlusVandy/MotherToMother pull request #73
Opened 2023-12-01 05:20 UTC by Joey2441-spec

New changes: 
<img width="451" alt="image" src="https://github.com/ChangePlusPlusVandy/MotherToMother/assets/53624798/068ce18e-da2c-4da9-b6ca-40124ed3a2bb">

<img width="451" alt="image" src="https://github.com/ChangePlusPlusVandy/MotherToMother/assets/53624798/c4ea818f-8e29-474f-a243-6a3e04133450">

Made agency required when not public.

2023-12-01 16:38 UTC, OliviaLiu417 approved these changes

2023-12-01 16:44 UTC, OliviaLiu417 requested changes
Change agency label to affiliation while not breaking the api call

2023-12-02 00:31 UTC, joseph-zou commented
I change it all to affiliation and removed unnecessary things. One issue is that I can't fix the api call code because that is part of the register connect branch which hasn't been pushed. So I will change it in the other branch.

2023-12-02 19:33 UTC, OliviaLiu417 commented
Could you also get rid of the corporate / foundation user type from the drop down? Thanks!

2023-12-02 19:47 UTC, OliviaLiu417 approved these changes

2023-12-02 19:47 UTC, merged